---
- name: CCDEMO
  hosts: all 
  become: ccdemo
  tasks:
    - name: Create a file called '/tmp/testfile.txt' with the content 'CCDEMO'.
      copy:
        content: CCDEMO_2
        dest: /tmp/testfile.txt
